server:
  port: 9191
spring:
  kafka:
    bootstrap-servers: sulky-01.srvs.cloudkafka.com:9094,sulky-02.srvs.cloudkafka.com:9094,sulky-03.srvs.cloudkafka.com:9094
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="e50001ig" password="9o1SdE_SMdeKpwa00fG9aT6GtBsHfwtz";
    consumer:
      group-id: e50001ig-consumers
      auto-offset-reset: latest
      properties.spring.json.trusted.packages: sample.kafka

  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
      function:
        definition: orderPurchaseEventProcessor;paymentEventSubscriber
      bindings:
        orderPurchaseEventProcessor-in-0:
          destination: e50001ig-orders
        orderPurchaseEventProcessor-out-0:
          destination: e50001ig-payments
        paymentEventSubscriber-in-0:
          destination: e50001ig-payments
        paymentEventSubscriber-out-0:
          destination: e50001ig-transactions
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    
